version: '3.4'

services:
  database:
    restart: always
    image: postgres:11.4-alpine
    container_name: planner-db
    ports:
      - "9050:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - reserved for config
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    # command: postgres -c shared_buffers=512MB -c effective_cache_size=1536MB -c work_mem=2621kB -c maintenance_work_mem=128MB
    # shm_size: '1gb'

  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - "9040:9040"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  app:
    user: root
    restart: always
    image: gradle:5.2.1-jdk8-alpine
    container_name: planner-app
    working_dir: /srv
    expose:
      - "9041"
    volumes:
      - gradle-cache:/home/gradle/.gradle
      - ./app:/srv:rw
    command: sh -c "chmod -R 777 /srv ; gradle clean bootJar ; java -Dserver.port=9041 -jar -Dspring.profiles.active=prod /srv/build/libs/server-1.0.0.jar"
    depends_on:
      - database

volumes:
  gradle-cache:
    external: false
  pgdata:
    external: false

networks:
  default:
    driver: bridge
