version: '3.4'

services:
  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  app:
    user: root
    restart: always
    image: gradle:5.2.1-jdk8-alpine
    working_dir: /srv
    expose:
      - "8080"
    volumes:
      - gradle-cache:/home/gradle/.gradle
      - ./app:/srv:rw
    command: sh -c "chmod -R 777 /srv ; gradle clean bootRun"

volumes:
  gradle-cache:
    external: false
