version: '3.4'

services:
  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
  app:
    restart: always
    image: gradle:5.2.1-jdk8-alpine
    working_dir: /srv
    expose:
      - "8080"
    volumes:
      - ./app:/srv:rw
    command: gradle clean bootRun